---
# tasks file for consul-agent-ansible
# https://github.com/entanet-devops/consul/blob/master/tasks/main.yml

- name: Ensure Consul service group exists
  group:
    name: "{{ consul_group }}"
    system: true
    state: present

- name: Ensure Consul service user exists
  user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    home: "{{ consul_data_dir }}"
    system: true
    state: present

- name: Ensure unzip is installed
  package:
    name: unzip
  state: present

- name: Ensure Consul directory structure is configured
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  with_items:
    - "{{ consul_config_dir }}"
    - "{{ consul_data_dir }}"
    - "{{ consul_bin_dir }}/bin"

- name: Check consul_bin
  stat: 
    path: '{{ consul_bin_dir }}/bin/consul'
  register: consul_bin

- name: "Get consul package"
  become: true
  become_user: root
  get_url:
    url: '{{ consul_url }}'
    dest: /tmp/{{ consul_zip }}
    checksum: '{{ consul_checksum }}'
    mode: 0644
  when: not consul_bin.stat.exists

- name: Fetch Consul
  unarchive:
    src: /tmp/{{ consul_zip }}
    dest: '{{ consul_bin_dir }}/bin'
    remote_src: true
  become: true
  become_user: "{{ consul_user }}"
  when: not consul_bin.stat.exists

- name: Deploy Consul service configuration
  template:
    src: config.json.j2
    dest: "{{ consul_config_dir}}/config.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  notify:
    - Reload consul

- name: Register Selenoid service with http check
  template:
    src: selenoid.j2
    dest: '{{ consul_config_path }}/consul.d/selenoid.json'
    owner: consul
    group: consul
    mode: 0644
  notify:
    - Reload consul

- name: Ensure the Consul service is enabled on boot
  service:
    name: consul
    enabled: yes