---
- name: Load a variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Choose platform based task
  include_tasks: '{{ platform }}'
  with_first_found:
    - 'system/{{ ansible_os_family }}.yml'
    - 'system/not-supported.yml'
  loop_control:
    loop_var: platform

- name: "Creating user for daemons"
  user:
    name: "selenoid"
    create_home: True
    home: "/home/selenoid"
    comment: "Selenoid user"
    shell: "/usr/sbin/nologin"
    state: "present"
  become: true

- name: "Setup home directory permissions"
  file:
    path: "/home/selenoid"
    mode: 0770

- name: config dir
  file:
    path: "{{ selenoid_config_dir }}"
    state: directory
    owner: selenoid
    group: selenoid
    mode: 777

- name: Install binary selenoid
  include: selenoid-binary.yml
  when: selenoid_binary == 'true'

- name: stop selenoid
  docker_container:
    name: selenoid
    state: absent
  ignore_errors: True

- name: stop cm
  docker_container:
    name: cm
    state: absent
  ignore_errors: True

- name: Docker pull cm and Selenoid
  include: selenoid.yml
  when: selenoid_binary == 'false'

- name: Create consul service file
  template:
    src: consul-selenoid-service.json.j2
    dest: "/etc/consul/consul.d/consul-selenoid-service.json"
  become: true