---
- name: Load variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Choose platform based task
  include_tasks: '{{ platform }}'
  with_first_found:
    - 'system/{{ ansible_os_family }}.yml'
    - 'system/not-supported.yml'
  loop_control:
    loop_var: platform

- name: Selenoid | Install certain python modules for docker
  pip:
    name: docker
    state: present
  register: installed_packages
  until: installed_packages is succeeded
  become: true

- name: Creating user for daemons
  user:
    name: selenoid
    create_home: true
    home: /home/selenoid
    comment: Selenoid user
    shell: /usr/sbin/nologin
    groups: docker
    state: present
  become: true

- name: Setup home directory permissions
  file:
    path: /home/selenoid
    mode: 0755

- name: Config dir
  file:
    path: '{{ selenoid_config_dir }}'
    state: directory
    owner: selenoid
    group: selenoid
    mode: 0755
  become: true

- name: Install binary selenoid
  include_tasks: selenoid-binary.yml
  when: selenoid_binary | bool

- name: stop selenoid
  docker_container:
    name: selenoid
    state: absent
  ignore_errors: true

- name: stop cm
  docker_container:
    name: cm
    state: absent
  ignore_errors: true

- name: Docker pull cm and Selenoid
  include_tasks: selenoid.yml
  when: not selenoid_binary | bool

- name: Create consul service file
  template:
    src: consul-selenoid-service.json.j2
    dest: /etc/consul/consul.d/consul-selenoid-service.json
  become: true
