---

- name: Download selenoid_linux_amd64 binary file
  get_url:
    url: "https://github.com/aerokube/selenoid/releases/download/{{ SELENOID_VERSION }}/selenoid_linux_amd64"
    dest: "{{ selenoid_config_dir }}/selenoid"
    owner: selenoid
    group: selenoid
    mode: a+x

- name: Docker pull images with chrome browser
  docker_image:
    name: "selenoid/vnc:chrome_{{ item }}"
  with_items:
    - "{{ SELENOID_CHROME_VERSION }}"

- name: Docker pull images with firefox browser
  docker_image:
    name: "selenoid/vnc:firefox_{{ item }}"
  with_items:
    - "{{ SELENOID_FIREFOX_VERSION }}"

- name: Docker pull images with opera browser
  docker_image:
    name: "selenoid/vnc:opera_{{ item }}"
  with_items:
    - "{{ SELENOID_OPERA_VERSION }}"

- name: config dir
  file:
    path: "{{ selenoid_config_dir }}/config"
    state: directory
    owner: selenoid
    group: selenoid
    mode: 777

- name: Create browsers config for selenoid
  template:
    src: browsers.json.j2
    dest: "{{ selenoid_config_dir }}/config/browsers.json"
    owner: selenoid
    group: selenoid
  become: true

- name: Create systemd file selenoid
  template:
    src: selenoid.service.j2
    dest: "/etc/systemd/system/selenoid.service"
    owner: selenoid
    group: selenoid
    mode: 0774
  become: true
  notify:
    - started selenoid.service