---
- name: Selenoid | Install certain python modules for docker
  pip:
    name: "docker-py"

- name: Install requirements packages
  package:
    name: '{{ requirements }}'
    state: present
  register: installed_packages
  until: installed_packages is succeeded
  become: True

- name: Enable amazon-linux-extras packages
  shell: "amazon-linux-extras install docker"
  become: true

- name: started docker.service
  systemd:
    state: started
    enabled: yes
    name: docker
  become: true
