---
- name: Become block
  block:
    - name: APT - install misc packages
      apt:
        name: '{{ requirements }}'
        state: present
      register: installed_packages
      until: installed_packages is succeeded

    - name: install deps
      apt:
        update_cache: true
        name:
          - python-pip
          - python3-pip
      register: installed_packages
      until: installed_packages is succeeded

    # - name: Selenoid | Uninstall docker module
    #   pip:
    #     state: absent
    #     name: docker
    #   register: uninstalled_packages
    #   until: uninstalled_packages is succeeded

    # - name: Selenoid | Install certain python modules for docker
    #   pip:
    #     name: docker
    #   register: installed_packages
    #   until: installed_packages is succeeded
  become: true
