---
- name: Become block
  block:
    - name: Install requirements packages
      yum:
        name: '{{ requirements }}'
        state: present
      register: installed_packages
      until: installed_packages is succeeded

    - name: Install python-pip
      yum:
        name: python-pip
        state: present
      register: installed_package
      until: installed_package is succeeded

    - name: started docker.service
      systemd:
        state: started
        enabled: true
        name: docker
  become: true
