---
- name: Become block
  block:
    - name: Install requirements packages
      yum:
        name: '{{ requirements }}'
        state: present
      register: installed_packages
      until: installed_packages is succeeded
  become: true
