---
- name: Become block
  block:
    - name: Selenoid | Install certain python modules for docker
      pip:
        name: docker-py
        state: present
      register: installed_packages
      until: installed_packages is succeeded

    - name: Install requirements packages
      package:
        name: '{{ requirements }}'
        state: present
      register: installed_packages
      until: installed_packages is succeeded

    - name: Enable amazon-linux-extras packages
      command: amazon-linux-extras install docker
      args:
        creates: /usr/bin/docker

    - name: started docker.service
      systemd:
        state: started
        enabled: true
        name: docker
  become: true
