---
- name: Selenoid | Install certain python modules for docker
  pip:
    name: docker-py
    state: present

- name: Install requirements packages
  package:
    name: '{{ requirements }}'
    state: present
  register: installed_packages
  until: installed_packages is succeeded
  become: true

- name: Enable amazon-linux-extras packages
  command: amazon-linux-extras install docker
  argv:
    creates: /usr/bin/docker
  become: true

- name: started docker.service
  systemd:
    state: started
    enabled: true
    name: docker
  become: true
